spring.application.name=api-gateway
server.port=8086

# Eureka Config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8084/eureka/
eureka.instance.prefer-ip-address=true


# ===============================
#   GATEWAY ROUTES
# ===============================

# Account Service
spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/accounts/**

# Transaction Service
spring.cloud.gateway.routes[1].id=transaction-service
spring.cloud.gateway.routes[1].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/transactions/**

# Notification Service
spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**
