server.port=8888
spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/Shravyajyothi21/banking-config-repo
spring.cloud.config.server.git.default-label=main

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8084/eureka/
management.endpoints.web.exposure.include=health,info

