server.port=8083
spring.application.name=transaction-service

spring.data.mongodb.uri=mongodb://localhost:27017/transactions_db

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8084/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Resilience4j
resilience4j.circuitbreaker.instances.accountServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.notificationServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.notificationServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationServiceCB.wait-duration-in-open-state=10s

