spring.application.name=transaction-service
server.port=8083

spring.data.mongodb.uri=mongodb://localhost:27017/transactions_db

# Eureka Configuration (Corrected)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8084/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}
# Expose actuator endpoints to see circuit breaker info
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================
# Resilience4j - Account CB
# =========================
resilience4j.circuitbreaker.instances.accountServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.accountServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.accountServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.accountServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.wait-duration-in-open-state=10s

# =============================
# Resilience4j - Notification CB
# =============================
resilience4j.circuitbreaker.instances.notificationServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.notificationServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.notificationServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationServiceCB.wait-duration-in-open-state=10s

